### ISSUE TITLE
import inf_cycle error

### ISSUE THREAD

**Issue by Heng14** [gautam678/Pix2Depth#21] opened 2018-07-30 10:41 UTC
Hello, really thank you for the nice job. I tried to run app.py but got a 'No module named 'inf_cycle'' error. Is that a file you forgot to release? Thank you for your help~

**Comment by adam-dziedzic** [comment] 2018-08-08 14:35
Yes, I think that you didn't commit inf_cycle into your repo. It'd be nice if you could add it.

**Comment by abhijay9** [comment] 2018-10-17 21:13
Hi,
The issue is still there,

    Traceback (most recent call last):
      File "main.py", line 12, in <module>
        from inf_cycle import test, test_dep
    ImportError: No module named inf_cycle

Please can you commit that file. It'll be really helpful.

**Comment by ShubhamMandwe** [comment] 2018-12-13 11:16
Hi @gautam678 can you please fix this issue. We're not able to find this module. Please commit it asap

Your idea and scripts are really nice.
Look forward to get more help from you. 

Thanks & Regards,
Shubham.

**Comment by keacifer** [comment] 2018-12-29 08:34
the same error

**Comment by gautam678** [comment] 2019-01-21 19:05
@maximus009  Could you help with this?

**Comment by maximus009** [comment] 2019-01-24 22:01
I think we need to link the cycle-gan implementation to solve this issue.

As most of you guessed, this implementation sits in another file that (for security reasons) could not be committed.

@gautam678 We can isolate the implementation and include it with what we can make publicly available.

**Comment by MeghaMaheshwari** [comment] 2019-01-28 19:06
@gautam678 : Is this issue resolved?

**Comment by amirea** [comment] 2019-09-24 20:54
Hello @maximus009, can't you link the same cycleGan implementation used for training? I'm missing something...

**Comment by lzq2369** [comment] 2019-12-02 02:28
PS C:\Pix2Depth-master> python .\app.py
Using TensorFlow backend.
Traceback (most recent call last):
  File ".\app.py", line 2, in <module>
    from main import pix2depth, portrait_mode, depth2pix
  File "C:\Pix2Depth-master\main.py", line 11, in <module>
    from config import CONFIG
ModuleNotFoundError: No module named 'config'

I can't find the config .could you help me?

**Comment by anasr91** [comment] 2020-07-11 12:07
@gautam678 & @Heng14 what should we do about this?

**Comment by MAli-Farooq** [comment] 2021-03-03 15:21
@gautam678 it still seems to be un-resolved ..

**Comment by gautam678** [comment] 2021-03-03 17:39
@MAli-Farooq  It's been a while since I looked at this repo. I don't plan on supporting this repo anymore.

**Closed as completed by gautam678** 2021-03-03 17:39 UTC

**Comment by jencyraj** [comment] 2021-03-09 00:22
pip install config
